### PR TITLE
Update Rollup.cls

### PR DESCRIPTION
**Pull request by bfalter**
Fix for https://github.com/jamessimone/apex-rollup/issues/607

### CODE REVIEW

**Comment by jamessimone** [comment]
This test (`RollupFlowTests.shouldReportErrorWhenConcatDelimiterSetAndNotConcat`) has been passing as-is since #597. This PR would be a breaking change as explained in [your first commit](https://github.com/bfalter/apex-rollup/commit/4bd4d12dea8fc92605bcc5061523bbe1965c91c5#comments).

What version of Apex Rollup are you running? I think perhaps it might help to clarify how you're experiencing the test failure, rather than this PR as it currently stands.

**Comment by bfalter** [comment]
@jamessimone 
1.6.29 with extra coverage plugin 0.0.22

**Comment by bfalter** [comment]
@jamessimone if that introduces a breaking change, perhaps it would make sense to add the additional space to the expected value rather than the .trim() method

**Comment by jamessimone** [comment]
@bfalter I can see that the Extra Code Coverage plugin needs to be regenerated, it was last regenerated off of 1.6.26, which was the version prior to #597 - that's why you're running into this. I can incorporate your suggestion in a more wholistic fashion with `v1.6.30` which I will release today

**Comment by bfalter** [comment]
@jamessimone sounds good to me!

**Pull request closed without merging**
